// src/components/Album_.tsx
import { useState } from 'react';

interface Slide {
  src: string;
  description?: string;
}

interface Props {
  slides: Slide[];
}

const Album = (props: Props) => {
  const { slides: images } = props;

  const [index, setIndex] = useState(0);
  const currentSlide = images[index];

  const prevSlide = () => {
    setIndex((i) => (i > 0 ? i - 1 : images.length - 1));
  };
  const nextSlide = () => {
    setIndex((i) => (i < images.length - 1 ? i + 1 : 0));
  };

  return (
    <div className="not-prose flex flex-col gap-2 border-neutral-800 pb-2">
      <img src={currentSlide.src} alt={currentSlide.description} />

      <p className="text-center text-sm italic text-neutral-500">
        {currentSlide.description}
      </p>

      <div className="flex flex-row justify-around">
        <button className="text-lg font-bold" onClick={prevSlide}>
          ←
        </button>

        <p className="text-lg font-bold">{`${index + 1}/${images.length}`}</p>

        <button className="text-lg font-bold" onClick={nextSlide}>
          →
        </button>
      </div>
    </div>
  );
};

export default Album;

// src/components/solidjs/Album.tsx
import { createSignal } from 'solid-js';

interface Slide {
  src: string;
  description?: string;
}

interface Props {
  slides: Slide[];
}

const Album = (props: Props) => {
  const { slides: images } = props;

  const [index, setIndex] = createSignal(0);
  const currentSlide = () => images[index()];

  const prevSlide = () => {
    setIndex((i) => (i > 0 ? i - 1 : images.length - 1));
  };
  const nextSlide = () => {
    setIndex((i) => (i < images.length - 1 ? i + 1 : 0));
  };

  return (
    <div class="pb-2 not-prose flex flex-col gap-2 border-neutral-800">
      <img src={currentSlide().src} alt={currentSlide().description} />

      <p class='text-center text-sm italic text-neutral-500'>{currentSlide().description}</p>

      <div class="flex flex-row justify-around">
        <button class="text-lg font-bold" onClick={prevSlide}>
          ←
        </button>

        <p class="text-lg font-bold">{`${index() + 1}/${images.length}`}</p>

        <button class="text-lg font-bold" onClick={nextSlide}>
          →
        </button>
      </div>
    </div>
  );
};

export default Album;
